clear;

voti_cred = input('Inserire le coppie (voto,crediti) per ogni esame dato: ');
sz = size(voti_cred);

if sz(1) > 1
    % Se vengono dati sotto forma di matrice a due dimensioni
    [mediana,media,media_pesata,voto_massimo,voto_minimo] = ...
        stud_stats(voti_cred(1:end,1),voti_cred(1:end,2),length(voti_cred));
else
    % Se vengono dati sotto forma di vettore
    [mediana,media,media_pesata,voto_massimo,voto_minimo] = ...
        stud_stats(voti_cred(1:2:end),voti_cred(2:2:end),length(voti_cred)/2);
end

fprintf(['Mediana:\t %2.0f\n'...
         'Media:\t\t %2.3f\n'...
         'Media pesata:\t %2.3f\n'...
         'Voto massimo:\t %2.0f\n'...
         'Voto massimo:\t %2.0f\n'],...
         mediana,media,media_pesata,voto_massimo,voto_minimo);